#!/bin/bash

# simplechroot

#
# Copyright (C) 2018 Caleb Woodbine <calebwoodbine.public@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

mountNode=false
_verbose=false
version=0.0.1

if [ ! "$(id -u)" = 0 ]
then
	echo "Error: you must be root to use this script."
	exit 1
fi

if [ -z "$args" ]
then
	args="/bin/bash"
fi

if (($# == 0))
then
	echo "Error: No args provided. Please run 'simplechroot -h' for help."
	exit 1
fi

function msg() {
# print if _verbose is true
if [ "$_verbose" = true ]
then
	echo $@
fi
}

function parse_rootDir() {
# resolve dir or node
rootDir="$_rootDir"
if [ ! -e "$rootDir" ]
then
	echo "Error: directory or node not found."
	trap "" EXIT
	exit 1
fi

if [[ "$_rootDir" = "/dev"* ]]
then
	_rootDir_basename=$(basename $_rootDir)
	if ! lsblk | grep -q "$_rootDir_basename" || [[ "$_rootDir_basename" = "loop"* ]] || ( [[ ! "${_rootDir_basename#${_rootDir_basename%?}}" = [[:digit:]] ]] && [[ ! $(dirname $_rootDir) = "/dev/mapper" ]] && [[ ! $(dirname $_rootDir) = "/dev/dm"* ]] )
	then
		echo "Error: please enter a valid root partition disk node (must be a partition)."
		exit 1
	fi
	mkdir -p /tmp/simplechroot-mount-root
	if mount | grep -q /tmp/simplechroot-mount-root || ! mount "$_rootDir" /tmp/simplechroot-mount-root
	then
		echo "Cannot mount '$_rootDir'."
		exit 1
	fi
	msg "Status: mounted '$_rootDir' to '/tmp/simplechroot-mount-root'."
	rootDir="/tmp/simplechroot-mount-root"
	mountNode=true

elif [ -d "$_rootDir" ] || [[ "$_rootDir" = "/dev"* ]]
then
	rootDir=$(readlink -f "$rootDir")
	return
else
	echo "'$_rootDir' is not a valid directory or node."
	exit 1
fi
}

function setupChroot() {
# bind mount points

msg "Setting up '$_rootDir'"
for point in dev proc sys run
do
	if ! mount --bind "/$point" "$rootDir/$point"
	then
		echo "Failed to mount '/$point' to '$rootDir/$point'; Unmounting all."
		unmountChroot
		exit
	fi
done
}

function unmountChroot() {
# unmount all binds
msg "Unmounting partitions"
for point in dev proc sys run
do
	if mount | grep -q "$rootDir/$point"
	then
		umount "$rootDir/$point" || echo "Failed to unmount '$rootDir/$point'"
	fi
done

if [ ! -z "$bootDir" ] && mount | grep -q "$rootDir"/boot
then
	umount -f "$rootDir"/boot
fi

if [ "$mountNode" = true ]
then
	umount "$rootDir"
fi
}

function validate_rootDir() {
# check if $_rootDir contains a standard Linux filesystem
for i in bin/bash boot dev etc home lib mnt proc root run sbin sys tmp usr var
do
	if [ -e "$rootDir/$i" ]
	then
		continue
	else
		echo "Cannot find standard Linux filesystem folders or programs."
		exit 1
	fi
done

if [ "$reinstallgrub" = true ]
then
	if [[ ! -e "$rootDir/usr/sbin/grub${grubver}-install" ]]
	then
		echo "Cannot find standard Linux filesystem folders or programs."
		echo "The system which you are trying to repair most likely uses grub2."
		echo "Try 'simplechroot -d $_rootDir -b $bootDir --reinstall-grub 2'"
		exit 1
	fi
fi

unset i
}

function parse_bootDir() {
# parse given boot node
if [[ "$bootDir" = "/dev"* ]]
then
	_bootDir_basename=$(basename $bootDir)
	if ! lsblk | grep -q "$_bootDir_basename" || [[ "$_bootDir_basename" = "loop"* ]] || ( [[ ! "${_bootDir_basename#${_bootDir_basename%?}}" = [[:digit:]] ]] && [[ ! $(dirname $bootDir) = "/dev/mapper" ]]  && [[ ! $(dirname $bootDir) = "/dev/dm"* ]] )
	then
		echo "Error: please enter a valid boot partition disk node (must be a partition)."
		exit 1
	fi
	return
fi

echo "Error: arg '-b' must be a node in '/dev'."
exit 1
}

function mount_bootDir() {
# mount boot node when given
if [[ "$bootDir" = "$_rootDir" ]]
then
	return
fi

if ! mount "$bootDir" "$rootDir"/boot
then
	echo "Error: failed to mount '$bootDir' to '$rootDir/boot'."
	exit
fi
}

# parse args
while [ $# -gt 0 ]
do
	case "$1" in
		-d)
			# root directory or node
			shift
			_rootDir="$1"
			;;

		-b)
			# boot directory or node
			shift
			bootDir="$1"
			;;

		--reinstall-grub)
			# grub reinstallation
			shift
			_grubver="$1"
			[ "$_grubver" = 2 ] && grubver="2" || grubver=""
			reinstallgrub=true
			if [ -z "$bootDir" ] || [ -z "$_rootDir" ]
			then
				echo "Error: arg '-b' and '-d' must be used. It is required for reinstalling grub."
				exit 1
			fi
			bootDir_base=$(lsblk -no pkname --path $bootDir)
			msg "Reinstalling grub${grubver} on '$bootDir_base'."
			args=("grub${grubver}-install $bootDir_base --recheck" "grub${grubver}-mkconfig -o /boot/grub${grubver}/grub.cfg")
			;;

		-c)
			# commands to run in chroot
			shift
			sendcommands=true
			args="$@"
			;;

		-v)
			# output progress
			_verbose=true
			;;

		*)
			# help menu
			echo "simplechroot ($version)"
			echo
			echo "Usage examples:"
			echo "	simplechroot -d /dev/sda2 -b /dev/sda1"
			echo "	simplechroot -d /mnt/rootMount"
			echo "	simplechroot -d /mnt/mapper/lvmPartition"
			echo "	simplechroot -d /mnt/rootMount -b /dev/sda1"
			echo "	simplechroot -d /dev/sda2 -b /dev/sda1 --reinstall-grub"
			echo "	simplechroot -d /mnt/rootMount -b /dev/sda1 -c 'ls /bin/.'"
			echo
			echo "==========================================================="
			echo "| -d               | mounted root partition or devfs node |"
			echo "| -b               | boot partition devfs node            |"
			echo "| -v               | make output verbose                  |"
			echo "| -c               | send a command to the chroot         |"
			echo "| --reinstall-grub | reinstall grub (requires -b)         |"
			echo "|                  | pass 2, for use in grub2-install     |"
			echo "==========================================================="
			echo
			echo "To find your disks, use 'fdisk -l' or your disk manager of choice."
			echo
			exit
			;;
	esac
	shift
done

if [ -z "$_rootDir" ]
then
	echo "Error: please enter root directory or node using the '-d' arg."
	exit 1
fi

if [ ! -z "$sendcommands" ] && [ ! -z "$reinstallgrub" ]
then
	echo "Error: please either use '-c' or '--reinstall-grub'"
	exit 1
fi

trap unmountChroot EXIT

# main process
parse_rootDir
validate_rootDir
if [ ! -z "$bootDir" ]
then
	parse_bootDir
	mount_bootDir
fi
setupChroot
for i in "${args[@]}"
do
	chroot "$rootDir" ${i[@]}
done