name: simplechroot
version: 1.1.0
summary: Chroot with ease.
description: >
  Chroot into a Linux system without any hastle

grade: stable
confinement: classic

architectures:
  - all

parts:
  simplechroot:
    plugin: dump
    source: simplechroot.zip

apps:
  simplechroot:
    command: usr/bin/simplechroot